name: nyc_taxi
version: "1.0.0"
profile: nyc_taxi

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  nyc_taxi:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: table
    marts:
      +materialized: table
